### ISSUE TITLE
能否解释每个txt文件的用途

### ISSUE THREAD

**Issue by Faith-Uchiha** [qweraqq/NLPCC2014_sentiment#1]
比如test.cn.labels.txt 看了内容，，我认为是带标注的测试数据集，不知道对不对。 顺便想问下这个测试数据集的标签你是用官方程序跑出来的吗？

**Comment by qweraqq** [comment]
sample.negative.txt
sample.positive.txt
官方的训练集

test.cn.txt
官方的测试集合，比赛时应该是没有标签的

test.label.cn.txt
官方的测试集标签，比赛后公布的

其他文件都是模型训练、评估过程中的中间文件

**Comment by Faith-Uchiha** [comment]
> sample.negative.txt
> sample.positive.txt
> 官方的训练集
> 
> test.cn.txt
> 官方的测试集合，比赛时应该是没有标签的
> 
> test.label.cn.txt
> 官方的测试集标签，比赛后公布的
> 
> 其他文件都是模型训练、评估过程中的中间文件

好的，感谢！
